### ISSUE TITLE
About example tcpdump

### ISSUE THREAD

**Issue by LuoZijun** [smoltcp-rs/smoltcp#109]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/717717/34400429-19be3dee-ebcc-11e7-9ce7-be9a113f6d07.png">

why has `checksum incorrect` error ?

this packet send by system, not me.

**Comment by whitequark** [comment]
TCP checksum offload.

**Comment by LuoZijun** [comment]
@whitequark 

https://github.com/m-labs/smoltcp/blob/master/src/wire/ip.rs#L777

but why checksum is invalid ?

i think this shoud't happend.

maybe recv raw packet `( socket(AF_PACKET, ...) ) ` has some mistake ?

**Comment by whitequark** [comment]
Google "TCP checksum offload". Basically, the OS puts zero in the checksum field, and since tcpdump is receiving packets from the OS, it also gets packets with such timestamps. But the NIC, before transmitting the packet, calculates the actual timestamp and substitutes it just in time.

**Comment by LuoZijun** [comment]
okay, thank u let me know that.

vbox doing that, i guess.

**Comment by whitequark** [comment]
Yes, hypervisors are typically capable of handling checksum offload.
