### ISSUE TITLE
Route broadcast packets directly

### ISSUE THREAD

**Issue by azenla** [smoltcp-rs/smoltcp#120]
When sending a packet to 255.255.255.255, routing should send directly, instead of to the gateway.
This is essentially a PR, except it's so trivial, I decided just to do an issue instead.

[Problem Code](https://github.com/m-labs/smoltcp/blob/master/src/iface/ethernet.rs#L875)

## Current

```rust
    fn route(&self, addr: &IpAddress) -> Result<IpAddress> {
        // Send directly.
        if self.in_same_network(addr) {
            return Ok(addr.clone())
        }
```

## Fixed

```rust
    fn route(&self, addr: &IpAddress) -> Result<IpAddress> {
        // Send directly.
        if self.in_same_network(addr) || addr.is_broadcast() {
            return Ok(addr.clone())
        }
```

**Comment by whitequark** [comment]
FYI it's quite a bit less work to merge this as a PR.

**Comment by kaendfinger** [comment]
Sorry about that @whitequark, I was on a slow network at the time, and cloning was taking a long time.
