### ISSUE TITLE
Routing, network address translation

### ISSUE THREAD

**Issue by canndrew** [smoltcp-rs/smoltcp#129]
Is this out of scope for this library? I'm implementing some of this stuff myself in a library that I plan to port to smoltcp. I'm wondering if I should try to move my implementations upstream at some point.

**Comment by whitequark** [comment]
Unclear. I'd need to look at your proposal to see if it makes sense in smoltcp.

**Comment by canndrew** [comment]
For example, there could be a `Nat<D>` type which wraps a `Device` and implements `Device`. Any IP packets sent from the underlying device get their source endpoint mapped to some global endpoint before being sent from the `Nat`. And vice-versa for incoming packets sent to the `Nat`.

A `Router` type could be constructed from a set of `Device`s and a set of routes. As you drive the router, any frame that gets read from one device gets dropped or written to another.

**Comment by batonius** [comment]
I would like to see routing in `smoltcp`, but I think it should be implemented on top of (or as a part of) a more general support for multiple interfaces, something we lack right now, otherwise, it makes little sense. There were some (quite vague) ideas discussed in #55, which overlap with your proposal to a significant extent, but I haven't come up with a specific design yet, so maybe you could contribute to that discussion as well.

**Comment by whitequark** [comment]
I agree with @batonius.

**Comment by astro** [comment]
> For example, there could be a Nat<D> type which wraps a Device and implements Device. Any IP packets sent from the underlying device get their source endpoint mapped to some global endpoint before being sent from the Nat. And vice-versa for incoming packets sent to the Nat.

In Linux NAT happens in the outgoing device path (`POSTROUTING` chain). There the outgoing address can be used naturally.

**Comment by Dirbaio** [comment]
Hello! As part of issue cleanup I'm closing inactive or already-answered "question" issues, since they're not actionable.

Note this doesn't mean questions aren't welcome. They still are! It's just that they shouldn't stay open forever.
