### ISSUE TITLE
use (or contribute to) crc library?

### ISSUE THREAD

**Issue by vitiral** [smoltcp-rs/smoltcp#13]
I noticed that you re-implement crc. Would you be interested in using a library instead (or contributing to it if it doesn't work for your needs)?

I just opened a PR for no_std support in mrhooray/crc-rs#13

**Comment by whitequark** [comment]
smoltcp does not implement any form of CRC. It implements an RFC 1071 checksum. In any case a dependency on crc-rs would be strictly a drawback, so no.
