### ISSUE TITLE
Add `core::hash::Hash` trait for `wire::Ipv4Address/Ipv6Address`

### ISSUE THREAD

**Issue by LuoZijun** [smoltcp-rs/smoltcp#130]
Add `core::hash::Hash` trait for `wire::Ipv4Address/Ipv6Address/IpAddress/IpCidr/Ipv4Cidr/Ipv6Cidr` ?

**Comment by whitequark** [comment]
Sure.

**Comment by LuoZijun** [comment]
okay, see https://github.com/m-labs/smoltcp/pull/131/files

**Comment by whitequark** [comment]
Thanks!
