### ISSUE TITLE
UDP socket buffer wastes space

### ISSUE THREAD

**Issue by phil-opp** [smoltcp-rs/smoltcp#138]
The rx buffer of `UdpSocket` being a `RingBuffer` of `PacketBuffer`s forces users to allocate much larger buffers than needed. If they want to be able to receive MTU sized packets, each `PacketBuffer` in the ring must have a MTU sized payload buffer. The problem is that a received UDP packet always fills a whole slot in the receive buffer, even if its payload is much smaller than the MTU. For example, if we allocate a two MTU sized packet buffers (so that we can receive two MTU sized packets), we can only receive two 10 byte UDP packets until the ring buffer is full. Most of the backing store is left unused.

A byte based buffer could utilize the available buffer space more effectively. For example, with a rx buffer size of 2*MTU we could either receive two MTU sized packets or hundreds of small packets. The `RingBuffer` already supports a byte based interface for tcp, so this part would be relatively easy.

The difficulty is that an UDP socket can receive data from multiple endpoints and should always return a the payload from a single packet on `recv` (instead of just a byte stream across packets like in TCP). My idea would be to use two ring buffers: one for the byte based backing storage and one for the metadata (PacketBuffer, packet size, packet start in byte buffer). This way, we could have separate limits for the amount of receivable bytes and the number of receivable packets. What do you think?

**Comment by whitequark** [comment]
Assuming you can do that without unsafe code, sure.
