### ISSUE TITLE
socket::set::Item is not exported publicly

### ISSUE THREAD

**Issue by adamgreig** [smoltcp-rs/smoltcp#14]
Right now `socket::set::Item` (used in `SocketSet::new`) is a public type inside the `set` module, but it is not publicly used in `socket`, so it's impossible to refer to this type.

I think this is basically the issue discussed [here](https://internals.rust-lang.org/t/pre-rfc-warn-about-inaccessible-types-in-public-function-signatures/5156).

It means you can do this:

```rust
let mut sockets_storage = [None];
let mut sockets = SocketSet::new(&mut sockets_storage[..]);
sockets_storage[0] = Some(1);
```

and the compiler infers the type of `sockets_storage` OK, and gives this error:
```
expected type `smoltcp::socket::set::Item<'_, '_>`
found type `{integer}`
```

but if you try and use that type:
```rust
let mut sockets_storage: [Option<smoltcp::socket::set::Item>; 1] = [None; 1];
```

you get
```
error: module `set` is private
```

This makes it really hard to statically allocate all the storage for smoltcp, as far as I can tell. Is there a nice way to do that? I'm running into a bunch of various pain points trying to allocate the storage statically, but I can't have it live on the stack (since it needs to live beyond the function call setting it up) and I don't have a heap available. There's a lot of `static mut X: Option<SliceArpCache> = None;` and then setting it to `Some(SliceArpCache::new(...))` during setup.

**Comment by whitequark** [comment]
> This makes it really hard to statically allocate all the storage for smoltcp, as far as I can tell. Is there a nice way to do that?

Yeah, this is a problem obviously. I am not sure how I missed that given that the examples should exercise these paths... I'll think about the solutions and get back to you.
