### ISSUE TITLE
Use standard library types where possible

### ISSUE THREAD

**Issue by canndrew** [smoltcp-rs/smoltcp#147]
I've noticed smoltcp defines its own `Ipv4Address` and `IpEndpoint` types instead of using the standard `Ipv4Addr` and `SocketAddr` types. Is there any good reason for this? It's kind of annoying to have to convert between the two.

**Comment by whitequark** [comment]
`#[no_std]`

**Comment by canndrew** [comment]
Oh, right.

Couldn't we define the types to be identical to the standard library types and then only use them if `#[no_std]` is being used, otherwise just re-export the standard library types?

**Comment by whitequark** [comment]
The standard library types have a different API that doesn't follow the way every other type in smoltcp is designed. Read the documentation for the wire module to see what I mean.

**Comment by whitequark** [comment]
That said, I would accept a PR that adds `From` and `Into` implementations, where possible.

**Comment by canndrew** [comment]
Here you go: https://github.com/m-labs/smoltcp/pull/149
