### ISSUE TITLE
Name types properly

### ISSUE THREAD

**Issue by canndrew** [smoltcp-rs/smoltcp#148]
A lot of the types in the `wire` module (and possibly the rest of the library, I haven't checked) are defined using one name then re-exported with another. This makes documentation and rustc error messages  confusing because (for instance) `EthernetAddress`, `IpAddress`, `Ipv4Address`, `Ipv6Address` are all just called `Address`. Would a PR be accepted to rename these types where they're defined? (I realize this could be considered a bug in rustc and rustdoc. But only arguably so, and it's not necessarily one that's going to get fixed anytime soon.)

**Comment by whitequark** [comment]
No, this is deliberate. This would add e.g. several hundred useless repeats of "Tcp" in tcp.rs. I don't want that.
