### ISSUE TITLE
Add an EthernetRepr type

### ISSUE THREAD

**Issue by canndrew** [smoltcp-rs/smoltcp#154]
I should be able to construct an ethernet frame using the `Repr` pattern, same as I can with IP packets.

**Comment by whitequark** [comment]
Doesn't seem very useful other than for completeness.

**Comment by canndrew** [comment]
It would be useful for me with the code I'm writing right now. I'll submit a PR for it.

**Comment by whitequark** [comment]
@dlrobertson I think you had an implementation for EthernetRepr, if @canndrew hasn't written one yet, I can probably merge that one.
