### ISSUE TITLE
Implement `As{Ref,Mut}<[u8]>` for packet types.

### ISSUE THREAD

**Issue by canndrew** [smoltcp-rs/smoltcp#157]
I can already call `.into_inner()` to extract the buffer from an `Ipv4Packet`/`EthernetFrame` etc. It should be possible to get a reference to the buffer without consuming the packet object.

**Comment by whitequark** [comment]
Sure, PR welcome.

**Comment by whitequark** [comment]
Though I don't think AsMut should be provided, this would break the guarantee that `new_checked` currently provides...
