### ISSUE TITLE
Use core::time::Duration

### ISSUE THREAD

**Issue by whitequark** [smoltcp-rs/smoltcp#182]
`std::time::Duration` was moved into `core`, so now we don't need to conditionally compile those conversions predicated on whether we have `--feature=std`.

**Comment by dlrobertson** [comment]
If `std::time::Duration` was moved to `std`, should we still roll our own `Duration` or should we just use the one provided in `core`?

**Comment by whitequark** [comment]
That's a good question! The `core` one has way too much resolution and is twice as big, so I'd say let's keep ours. We can always deprecate it.

**Comment by dlrobertson** [comment]
:+1: makes sense
