### ISSUE TITLE
Stalled TCP connection because window update is not announced after reading

### ISSUE THREAD

**Issue by pothos** [smoltcp-rs/smoltcp#199]
Only ACKs generated by `dispatch` are updating `remote_last_win` but not the ACKs generated by  `process`, failing to keep track of the last announced receive window. This leaves `window_to_update` to return false in `dispatch` after the RX buffer was emptied, thus not announcing that the receive window is not zero anymore after reading from the RX buffer → Connection is stalled if keep-alive is off.

I will submit a patch now.

Actually I also want to use this issue to ask if _Probing Zero Windows_ should be added to the list as **not supported**: https://tools.ietf.org/html/rfc1122#page-92 (This requires a timer for a sender which got a zero window announced from the receiver.)

**Comment by whitequark** [comment]
Thanks, excellent catch!

> Actually I also want to use this issue to ask if Probing Zero Windows should be added to the list as not supported: https://tools.ietf.org/html/rfc1122#page-92 (This requires a timer for a sender which got a zero window announced from the receiver.)

Yes. That, or an implementation.
