### ISSUE TITLE
Build broken for `default-features=false`

### ISSUE THREAD

**Issue by phil-opp** [smoltcp-rs/smoltcp#2]
Hi! First of all, thanks a lot for creating this library. It seems like a great fit for embedded and OS development.

Unfortunately, it no longer compiles with `default-features=false`, since 
[`ManagedSlice::Owned`](https://docs.rs/managed/0.2.1/managed/enum.ManagedSlice.html) is only available with `use_std` or `use_collections`.

```
error: no associated item named `Owned` found for type `managed::ManagedSlice<'_, _>` in the current scope
  --> /…/smoltcp-ebf9e93b1271bd34/874d192/src/socket/set.rs:64:13
   |
64 |             ManagedSlice::Owned(ref mut sockets) => {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

(I think it would be a good idea to add an additional travis build config for `default-features=false` to prevent similar issues in the future.)

**Comment by whitequark** [comment]
Fixed

**Comment by phil-opp** [comment]
Thanks!
