### ISSUE TITLE
socket: accepts function does not need the entire IpRepr

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#202]
Each socket type (`ICMP`, `UDP`, and `TCP`) has a corresponding `accetps` function that determines if the given packet was meant for the current socket. Currently this function accepts the entire `IpRepr`, but only the source address and destination address are used.

**Comment by whitequark** [comment]
Is this a problem? We already have the `IpRepr`.

**Comment by dlrobertson** [comment]
It isn't really a problem. I was primarily thinking of this as unused information. In particular I was thinking about the case where the packet is something like IPv6 > Hop-by-Hop > UDP. In this case the UDP socket `accepts` function will accept the `IpRepr` with a `next_header` value of Hop-by-Hop, but obviously `repr` would be a `UdpRepr`.

**Comment by whitequark** [comment]
Yeah, that check is already done in EthernetInterface, so I didn't add it to `accepts` as redundant. We may add it for completeness, although it feels a bit pointless.

**Comment by Dirbaio** [comment]
Hello! As part of issue cleanup I'm closing inactive or already-answered "question" issues, since they're not actionable.

Note this doesn't mean questions aren't welcome. They still are! It's just that they shouldn't stay open forever.
