### ISSUE TITLE
Implement Future for EthernetInterface

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#208]
[futures] is `#[no_std]`, so it may be worthwhile to implement `Future` for `EthernetInterface` if a feature is enabled.

[futures]: https://docs.rs/futures/0.2.1/futures/

**Comment by whitequark** [comment]
:+1:

**Comment by Dirbaio** [comment]
#394 added support for attaching `Waker`s to sockets, which is everything required to allow building async APIs on top of smoltcp. The smoltcp project itself won't be adding further async support due to reasons detailed in that PR.
