### ISSUE TITLE
RFC: multiple routes

### ISSUE THREAD

**Issue by progval** [smoltcp-rs/smoltcp#209]
As asked in #207, I'm opening an RFC issue about multiple routes.

I created a naive implementation of routes [here](https://github.com/m-labs/smoltcp/compare/master...ProgVal:naive-routes), based on simply iterating over a managed slice.

Of course, there are probably more efficient ways to do it. Any thoughts?

**Comment by whitequark** [comment]
Using a managed::ManagedMap would be a first step.

**Comment by ProgVal** [comment]
It's not really a map, you would have to iterate through all keys

**Comment by whitequark** [comment]
ManagedMap performs binary search on bare no_std and uses a BTreeMap when alloc is available. It never just iterates through every key.

**Comment by ProgVal** [comment]
Indeed, sorry.

So what you're thinking of is making `ManagedMap`'s binary-search-related functions public, so we can use it in the route lookup, where we don't need an exact match (as opposed to a map)?

**Comment by whitequark** [comment]
No, the API shouldn't deviate that much. `ManagedMap` needs to gain BTreeMap's `range` method.

**Comment by ProgVal** [comment]
Closed by #219
