### ISSUE TITLE
RFC: Adding support for repeated NDISC options

### ISSUE THREAD

**Issue by progval** [smoltcp-rs/smoltcp#211]
I noticed some code duplication in `NdiscOptions`'s handling: each variant of `Message` has to do its own loop over options, to find `SourceLinkLayerAddr` and possibly other options. `Message::Redirect` handling also had code that also exists `ndiscoption.rs`.

So I factorized all this, by adding an iterator structure over NDISC options, with enough room to store up to 32 options. My guess is that it should be enough, but I am not sure (Only `Prefix information` should be used more than once. Do you know if there are routers that announce more than 31 prefixes at the same time?)
[Here is a diff](https://github.com/ProgVal/smoltcp/commit/4bb602f83f8c4552930f345404aac8cd60d48465)

I also tried to implement that iterator with a `ManagedSlice`, but that requires to pass a pre-allocated slice through `EthernetInterface`'s API, and I find that messy.

Do you have better ideas to do this?

**Comment by whitequark** [comment]
Why does the iterator need to use a fixed size slice? This seems quite ugly to me.

**Comment by ProgVal** [comment]
Sorry, I forgot to mention this. I can't allocate on the heap without requiring `alloc` or `std`.

**Comment by whitequark** [comment]
Yeah, but can't you borrow a slice?

**Comment by ProgVal** [comment]
It works to create a `NdiscOptions` or a `NdiscOptionsRepr` from scratch, but not with `NdiscOptionsRepr::parse`, because we need another slice, and I don't know where to get it from

**Comment by dlrobertson** [comment]
Or a macro could work too.

**Comment by dlrobertson** [comment]
The real downside with flattening the options into the `NdiscRepr` like we currently do is `) it causes us to only know the options included in the `Repr` and 2) we keep duplicates. E.g. a Router Advertisement with two Prefix Information options will only result in a `Repr` with one Prefix Information option.

**Comment by ProgVal** [comment]
We could keep duplicates, but only a fixed number of them, known at compile time. Whereas in the RFC, the only limit is the MTU

**Comment by whitequark** [comment]
Do I understand it correctly that right now we handle any number of options just fine on no_std, but with this refactoring, we will be limited to something that is less than what RFC allows? This seems clearly bad to me.

**Comment by ProgVal** [comment]
No, right now, only one Prefix Information option is handled.

**Comment by whitequark** [comment]
OK, I'll need to take a closer look at this.

**Comment by dlrobertson** [comment]
> we will be limited to something that is less than what RFC allows

Yes the RFC allows for multiple options, but we do not currently support it.

> There can also be multiple instances of the same option in a message (e.g., Prefix Information options). [1]

[1]: https://tools.ietf.org/html/rfc4861#section-9

**Comment by dlrobertson** [comment]
After spending some time reviewing the linux kernel, it seems that the linux kernel does not allow for repeated NDISC options.

```c
struct ndisc_options *ndisc_parse_options(const struct net_device *dev,
                                          u8 *opt, int opt_len,
                                          struct ndisc_options *ndopts)
{
        ...
                switch (nd_opt->nd_opt_type) {
                case ND_OPT_SOURCE_LL_ADDR:
                case ND_OPT_TARGET_LL_ADDR:
                case ND_OPT_MTU:
                case ND_OPT_NONCE:
                case ND_OPT_REDIRECT_HDR:
                        if (ndopts->nd_opt_array[nd_opt->nd_opt_type]) {
                                ND_PRINTK(2, warn,
                                          "%s: duplicated ND6 option found: type=%d\n",
                                          __func__, nd_opt->nd_opt_type);
                        } else {
                                ndopts->nd_opt_array[nd_opt->nd_opt_type] = nd_opt;
                        }
                        break;
```

So I don't think it is unreasonable that we also do not allow duplicate options.

**Comment by whitequark** [comment]
@dlrobertson Doing the same thing as Linux seems good to me.
