### ISSUE TITLE
Improve ChecksumCapabilities for a IPv4/IPv6 environment

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#213]
The [ChecksumCapabilities] struct currently contains the members `udpv4` and `tcpv4` that will be used for IPv6 packets as well as IPv4 packets. These members should be changed to `udp` and `tcp` if they should be used for both IPv6 and IPv4. ~~If it is possible that we can only offload udp or tcp checksums for one IP version and not the other, the `udpv6` and `tcpv6` members should be added and the [UdpRepr::parse] and [TcpRepr::parse] functions should be updated accordingly.~~

[ChecksumCapabilities]: https://github.com/m-labs/smoltcp/blob/master/src/phy/mod.rs#L157-L167
[TcpRepr::parse]: https://github.com/m-labs/smoltcp/blob/fb96b3cdc1ba85dbb2cfbda1f1ae9cb10768980d/src/wire/tcp.rs#L654
[UdpRepr::parse]: https://github.com/m-labs/smoltcp/blob/fb96b3cdc1ba85dbb2cfbda1f1ae9cb10768980d/src/wire/udp.rs#L209

**Comment by whitequark** [comment]
Let's just rename those to `udp` and `tcp`. If some hardware supports checksums for IPv4 but not IPv6, the driver can just disable offload to both. I feel like simplicity is more important than supporting such crap in an optimal way.
