### ISSUE TITLE
Change signature of `poll_at` for sockets

### ISSUE THREAD

**Issue by barskern** [smoltcp-rs/smoltcp#215]
The purpose of `poll_at` is to return a hint to the caller when the socket should be polled. Hence when is it most likely that the socket will have updates/changes that need to be executed.

The current implementation of `poll_at` has the following signature:

```rust
pub(crate) fn poll_at(&self) -> Option<Instant>
```

As proposed by @whitequark it could be changed to something like
```rust
pub(crate) fn poll_at(&self) -> PollAt
```
where `PollAt` is defined as
```rust
enum PollAt {
    At(Instant),
    Now,
    Never,
}
```
I was thinking that it would be worthwhile to perhaps discuss the signature of `PollAt`.

As a newcomer to this project, when I see `PollAt::Never`, I think that the socket will never be polled again. However as explained in #214, when the previously similar state `None` is returned from `poll_at`, the program is blocked until a new packet arrives. Hence I propose the following signature:
```rust
enum PollAt {
    At(Instant),
    Now,
    Block,
}
```
Any thoughts? @whitequark @dlrobertson @pothos

**Comment by whitequark** [comment]
> the program is blocked until a new packet arrives

"Block" is really misleading because smoltcp doesn't have blocking I/O anywhere, it's fundamentally event-driven. How about...

```
enum PollAt {
    Now,
    Time(Instant),
    Ingress
}
```

where "ingress" means an incoming packet.

**Comment by barskern** [comment]
Yeah I like that signature better. Ingress is a new word to me, however it fits the need. When looking up the definition it makes sense.

> "Block" is really misleading because smoltcp doesn't have blocking I/O anywhere

Isn't the [`smoltcp::phy::sys::wait`](https://github.com/m-labs/smoltcp/blob/9a7318d1e6ae68c6fe40b007395f34f0c6550724/src/phy/sys/mod.rs#L23) there for providing this? I know it's conditionally compiled, however it is re-exported within smoltcp.

**Comment by barskern** [comment]
Ah okay, then I understand that `Block` is misleading. Using you're latest proposal for now:
```rust
enum PollAt {
    Now,
    Time(Instant),
    Ingress,
}
```
