### ISSUE TITLE
strange exhaustion with packet buffer enqueue?

### ISSUE THREAD

**Issue by birkenfeld** [smoltcp-rs/smoltcp#245]
I'm receiving two alternating messages (`start` and `stop`) on a UDP socket. The third cannot be processed. I added some logging to `PacketBuffer::enqueue`, seen in the debug output here:
```
[DEBUG] full: false, window: 6000, contig_window: 6000, size: 5
[DEBUG] full: false, window: 6000, contig_window: 5995, size: 4
[DEBUG] full: false, window: 6000, contig_window: 5996, size: 5
[DEBUG] cannot process ingress packet: buffer space exhausted
```
The third packet triggers the condition here:
```
        if window < size || (window != contig_window && window - contig_window < size) {
            return Err(Error::Exhausted)
        }
```
because `window - contig_window == 4 < size == 5`. But as far as I understand, having a contiguous window larger than `size` cannot be an exhaustion condition?

**Comment by whitequark** [comment]
Which version of smoltcp?

**Comment by whitequark** [comment]
@dlrobertson Can you please take a look? Something's screwy with that condition.

**Comment by dlrobertson** [comment]
Yup, that logic seems off...

**Comment by birkenfeld** [comment]
FWIW, it's revision 216c393 (the switch to `managed` 0.7 breaks with my pegged nightly).

**Comment by dlrobertson** [comment]
@birkenfeld thanks for pointing this out. The linked PR fixes this.
