### ISSUE TITLE
New crates.io release?

### ISSUE THREAD

**Issue by phil-opp** [smoltcp-rs/smoltcp#259]
The latest crates.io release (version 0.4.0) is from September 2017. Are there any plans to release a new version?

**Comment by whitequark** [comment]
Yep, I will handle this soon-ish.

**Comment by therealprof** [comment]
Hey guys, sorry for pinging in here. Any news about that release? Would be great if we could use a current version in other crates...

**Comment by whitequark** [comment]
0.5.0, sorry for the delay
