### ISSUE TITLE
Move to rust 2018 edition

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#271]
Get all the latest and greatest by moving to rust 2018 edition.

**Comment by whitequark** [comment]
This would be a problem for M-Labs because the ARTIQ Rust is not yet at the version that has the edition.

**Comment by crawford** [comment]
Crates can use independent editions. smoltcp can switch to 2018 while the rest of your code stays on 2015. It works quite well in practice (I'm already using a mix of 2018 and 2015 with smoltcp).

**Comment by jbg** [comment]
> The problem is that M-Labs has a fork of rustc which is not recent.

(out of interest, how come? Can the changes be contributed upstream?)

Would a PR be accepted for 2018 edition yet, or are you still using an older rustc internally?

**Comment by whitequark** [comment]
> (out of interest, how come? Can the changes be contributed upstream?)

No. M-Labs is using OpenRISC, which has a fork of LLVM, fork of Clang, and fork of rustc to support them both. There are currently neither resources nor people to upstream the OpenRISC backend in LLVM so it is unlikely that this will change unless M-Labs migrates to RISC-V.

However, that fork can be upgraded, which might be the simplest solution.

**Comment by hartytp** [comment]
> However, that fork can be upgraded, which might be the simplest solution.

Yes, it would be a shame if forcing smoltcp to use an old version of rust put off wider community usage/contributions.

**Comment by Dirbaio** [comment]
ping @whitequark Has this changed since? Should we upgrade to Rust 2018 now?

**Comment by whitequark** [comment]
Yep, absolutely do go ahead and upgrade.
