### ISSUE TITLE
manually adding neighbor entries

### ISSUE THREAD

**Issue by derkbell** [smoltcp-rs/smoltcp#273]
Hi,

I'm in a very specific case where I'm unable to send any ARP packets and I can only send a very specific type of UDP packet. The program I'm writing has a priori knowledge of the gateway IP and MAC address, so I would like to populate a NeighborCache with said IP and MAC address, but I'm unable to do so as the NeighborCache::fill method is public only to the crate so this fails:
```rust
let mut neighbor_cache = NeighborCache::new(BTreeMap::new());
neighbor_cache.fill(
  IpAddress::v4(192,168,1,1), 
  EthernetAddress::from_bytes(&[0u8, 0u8, 0u8, 0u8, 0u8, 2u8]), 
  Instant::from_secs(3600)
);
```

 Is there a way to do this? (I've also tried prefilling the BTreeMap but the Neighbor struct has private fields so that doesn't work either)

Thanks,
Derk

**Comment by whitequark** [comment]
I think prefilling the neighbor cache is a perfectly valid, albeit specific, request, and we can safely make the `fill` method public.
