### ISSUE TITLE
cannot implement Device outside of crate

### ISSUE THREAD

**Issue by derkbell** [smoltcp-rs/smoltcp#275]
Hi,

I'm currently implementing TPACKET_V3 / mmap RX_RING_BUFFER on top of the raw socket. I've setup a new crate that implements the Device trait. However, the capabilities method of this trait requires a return type of DeviceCapabilities, which has a private field "dummy". Rust doesn't allow me to implement this, even when using DeviceCapabilities::default(). This issue will also occur for the ChecksumCapabilities struct.

The comments specifically mention that the dummy field is there for a reason. What would be the right way to proceed here? 

Furthermore, it would be useful to access some of the consts and functions defined in phy::sys, for the sake of DRY, but the sys module is also private. These methods can easily be duplicated, but I'm wondering if it would be better to create a ring buffer variant of the raw socket within the smoltcp crate?

Thanks,
Derk

**Comment by whitequark** [comment]
The dummy field is there as a workaround for #44109. What is the error you're getting? I've definitely been able to implement that trait outside of the crate; I'm not sure if it's a recent rustc change?

**Comment by derkbell** [comment]
Yeah, my mistake, I was using 
```
DeviceCapabilities {
  max_transmission_unit: self.mtu,
 ..DeviceCapabilities::default() 
}
```

where I should have used something like
```
let mut caps = DeviceCapabilities::default();
caps.max_transmission_unit = self.mtu;
```

Thanks for checking
