### ISSUE TITLE
UDP checksum may be optional in IPv4

### ISSUE THREAD

**Issue by 197g** [smoltcp-rs/smoltcp#280]
# Issue

When the checksum in a UDP packet is `0`, it should be treated as if the checksum check was successful. Currently, verifier and pretty printer checks this more strictly. Note that this is not true for IPv6, where it is specified that the upper layer checksum must not be elided for UDP.

This seems to be a bug in the implementation, which contains code for special casing this checksum verification but that code does not actually lead to any elided checks.

## Workaround

A custom `Phy` implementation can pretend to work with offloaded checksums, i.e. `Checksum::None`, in its udp configuration in case it only expect IPv4 traffic or disable receive checks only.

## References

UDP: https://tools.ietf.org/html/rfc768 (directly above User Interface section)
IPv6: https://tools.ietf.org/html/rfc2460#section-8.1

**Comment by dlrobertson** [comment]
I'm pretty sure we already do this in the UDP `Repr` [here](https://github.com/m-labs/smoltcp/blob/master/src/wire/udp.rs#L215-L227). Do you have example code that causes this behavior?

**Comment by HeroicKatora** [comment]
That match looks broken to me. Both arms resolve to `Err(Error::Checksum)`, independent of the match or the conditional.

**Comment by HeroicKatora** [comment]
Not directly, just noticed it in the packet dump of a custom `Phy` implementation when wrapped in `phy::EthernetTracer`. Thus also hard to reproduce without the physical phy. I'll try to get something reproducible if possible.

**Comment by HeroicKatora** [comment]
I realize this bugreport is in an awkward state without reproduction, treat it as a mental note until I get back to it with a reproduction, the linked implementation looks good.

**Comment by dlrobertson** [comment]
> That match looks broken to me. Both arms resolve to Err(Error::Checksum), independent of the match or the conditional

True. It probably should not return an error in the first arm

**Comment by HeroicKatora** [comment]
> > That match looks broken to me. Both arms resolve to Err(Error::Checksum), independent of the match or the conditional

> True. It probably should not return an error in the first 

It's just more confusing than necessary, as it's a double negation. The control flow could be:

```
match (src_addr, dst_addr) {
    // ... except on UDP-over-IPv4, where it can be omitted.
    #[cfg(feature = "proto-ipv4")]
    (&IpAddress::Ipv4(_), &IpAddress::Ipv4(_)) if packet.checksum() == 0 => (),
    _ => return Err(Error::Checksum)
}
```

**Comment by HeroicKatora** [comment]
Minimal reproduction

```
use smoltcp::wire::{IpAddress, Ipv4Address};

fn main() {
    let packet: &[u8] = &[
        0x00, 0x42, 0x00, 0x80, // Src post, dst port
        0x00, 0x08, 0x00, 0x00]; // length, checksum
    let packet = smoltcp::wire::UdpPacket::new_checked(packet).unwrap();
    let verify = packet.verify_checksum(
        &IpAddress::Ipv4(Ipv4Address::new(127, 0, 0, 1)),
        &IpAddress::Ipv4(Ipv4Address::new(127, 0, 0, 2)));
    assert!(verify, "Checksum can be zeroed in IPv4");
}
```

**Comment by dlrobertson** [comment]
Ah, so this issue would be to move the conditional checks based on IPv4 into `verify_checksum` instead of in `Repr::parse`.

**Comment by HeroicKatora** [comment]
> Ah, so this issue would be to move the conditional checks based on IPv4 into verify_checksum instead of in Repr::parse.

I guess that is ultimately proper, although I didn't really intend it. Reproduction for `parse` as used in `EthernetInterface`, which doesn't require moving the check:

```
use smoltcp::phy::ChecksumCapabilities;
use smoltcp::wire::{IpAddress, Ipv4Address, UdpPacket, UdpRepr};

fn main() {
    let packet: &[u8] = &[
        0x00, 0x42, 0x00, 0x80,
        0x00, 0x08, 0x00, 0x00];
    let packet = UdpRepr::parse(
        &UdpPacket::new_checked(packet).unwrap(),
        &IpAddress::Ipv4(Ipv4Address::new(127, 0, 0, 1)),
        &IpAddress::Ipv4(Ipv4Address::new(127, 0, 0, 2)),
        &ChecksumCapabilities::default());
    assert!(packet.is_ok());
}
```
