### ISSUE TITLE
A total size of one packet or a total size of all packets?

### ISSUE THREAD

**Issue by hirrolot** [smoltcp-rs/smoltcp#298]
The `PacketBuffer::new` function is defined as:
```rust
pub fn new<MS, PS>(metadata_storage: MS, payload_storage: PS) -> PacketBuffer<'a, 'b, H>
        where MS: Into<ManagedSlice<'a, PacketMetadata<H>>>,
              PS: Into<ManagedSlice<'b, u8>>,
```

And its description says:
> Metadata storage limits the maximum number of packets in the buffer and payload storage limits the maximum total size of packets.

What actually means "the maximum total size of packets"? It might have two different meanings:
 1) The total size of ALL packets in a buffer;
 2) The total size of a single packet.

Which one of these meanings did you mean?

**Comment by whitequark** [comment]
> 1. The total size of ALL packets in a buffer;

This one. It's a ring buffer, where the size of the backing storage matters.

**Comment by Gymmasssorla** [comment]
Thank you
