### ISSUE TITLE
panic decoding DHCP domain name server option

### ISSUE THREAD

**Issue by cjbe** [smoltcp-rs/smoltcp#305]
Using the current smoltcp master, I get a panic during parsing a DHCP response:
```
panicked at 'index out of bounds: the len is 3 but the index is 3', C:\scratch\smoltcp\src\wire\dhcpv4.rs:749:25
```
This panic is from parsing the DHCP option field OPT_DOMAIN_NAME_SERVER [here](https://github.com/m-labs/smoltcp/blob/1ada3da5aa33917daf891dda2242d7f5beadfb10/src/wire/dhcpv4.rs#L743-L751)

The panic occurs as my DHCP server is broadcasting 4 DNS server addresses, and the code here iterates through the complete list of 4 DNS servers but tries to store the parsed addresses into an array of fixed length 3.

In my case the data in the options field is:
`[163, 1, 74, 6, 163, 1, 74, 7, 163, 1, 74, 3, 163, 1, 74, 4]`
This is valid, as [per the RFC](https://tools.ietf.org/html/rfc2132#page-6) the only requirements are a minimum length of 4 octets, and length a multiple of 4 octets (i.e. there is no maximum length).

**Comment by whitequark** [comment]
Sounds like we should add fuzzing for DHCP packets too.

**Comment by cjbe** [comment]
@whitequark would you accept a PR to only use the first 3 name servers supplied by the DHCP server? This is not a long term solution, but seems useful in the short term. (This seems to be what the current code is trying to implement at the moment with its fixed array of 3 DNS servers)

**Comment by whitequark** [comment]
Yes, with a test for the panic.
