### ISSUE TITLE
Broadcast IP resolving shouldn't happen via ARP cache

### ISSUE THREAD

**Issue by steffengy** [smoltcp-rs/smoltcp#33]
When sending an UDP broadcast packet via an `UdpSocket`,
I noticed that smoltcp attempted to check the ArpCache for `255.255.255.255`
and therefore send an ARP request for that IP, which I believe to be unusual.

I think insteadof calling `ArpCache::lookup` a general lookup-function
should be called, which handles this (`255.255.255.255` to MAC `[0xff; 6]` ) aswell
as other possible exceptions in the future.

Does that sound like the right approach?
I'd be fine with implementing it, but wanted some feedback first.

**Comment by whitequark** [comment]
Fixed as a side effect of 8ae9b21b.
