### ISSUE TITLE
Don't send window updates if remote side has closed the connection?

### ISSUE THREAD

**Issue by Dirbaio** [smoltcp-rs/smoltcp#358]
I've noticed that smoltcp is sending window updates after receiving a FIN. For example:

- Remote endpoint sends us a bunch of data.
- Remove endpoint sends FIN
- We ACK the data and the FIN, with reduced window size.
- Application reads the data from the TcpSocket.
- We send a window update ACK, with the now larger window.

It looks to me that this last ACK might be avoidable? If we've received a FIN, this means the remote side is not going to send more data, so they shouldn't care about the window size anymore.

I'm not sure whether the RFCs allow this though. I'm opening this issue to discuss. If we decide to do this, I can send a PR.

**Comment by whitequark** [comment]
I'm afraid I no longer remember enough context offhand to discuss this.
