### ISSUE TITLE
Document table broken at `docs.rs`

### ISSUE THREAD

**Issue by luojia65** [smoltcp-rs/smoltcp#361]
This is a minor document issue: https://docs.rs/smoltcp/0.6.0/smoltcp/#packet-and-representation-layer-support

<img width="1043" alt="图片" src="https://user-images.githubusercontent.com/40385009/85863385-a9b05e80-b7f5-11ea-9c3c-b06dda5b4154.png">

The markdown table here seems failed to render.

**Comment by whitequark** [comment]
I think it's fixed in the latest release, we probably need to issue another.
