### ISSUE TITLE
Is the poll/send-receive/phy_wait pattern ok?

### ISSUE THREAD

**Issue by lattice0** [smoltcp-rs/smoltcp#365]
a

**Comment by whitequark** [comment]
> On all examples of usage of SmolTCP, I've seen this pattern

IIRC, I didn't put a great amount of thought into it--it was just something to get the examples working.

**Comment by rickpayne** [comment]
Any thoughts on how to handle an interface such as a virtio vring where packets arrive asynchronously and should be pushed into the lower part of the stack at that point? In my case, I dont have an fd to select on in the phy_wait style.
I'm fairly new to rust, so probably still have a 'c' mindset, where we get the interrupt, marshall the buffers and then pass them to the next later up with some reference to the source interface...

**Comment by whitequark** [comment]
> Any thoughts on how to handle an interface such as a virtio vring where packets arrive asynchronously and should be pushed into the lower part of the stack at that point? In my case, I dont have an fd to select on in the phy_wait style.

It depends on the overall structure of your application. Something as simple as busy-waiting on a virtio empty flag would work, but you probably want to integrate that with scheduling of any other work your application does.

**Comment by Dirbaio** [comment]
Hello! As part of issue cleanup I'm closing inactive or already-answered "question" issues, since they're not actionable.

Note this doesn't mean questions aren't welcome. They still are! It's just that they shouldn't stay open forever.
