### ISSUE TITLE
TcpSocket::connect does not properly handle an already connected socket

### ISSUE THREAD

**Issue by ryan-summers** [smoltcp-rs/smoltcp#366]
It appears that smoltcp does not properly handle an unexpected ACK when in the SYNC-SENT state. This results in the TCP socket being in an unusable state.

These conditions are described [here](https://serverfault.com/questions/733681/server-sends-ack-in-response-to-syn-causing-a-reset-in-tcp-request-from-the-clie), but the basics are that a previous connection (which was not properly terminated with a FIN) results in the server having some established TCP state (server is in ESTABLISHED).

When the client sends the SYN packet, the server acknowledges with an ACK#x, which is invalid to receive in the SYNC-SENT state. `smoltcp` should recognize this state and instead send a RST to the server to properly terminate the previous connection. It should then restart the SYN handshake to establish a connection with the server.

Sample of wireshark capture showing the error
![image](https://user-images.githubusercontent.com/8771450/89767613-9aae1300-dafa-11ea-8521-fb0f9477be6f.png)

**Comment by ryan-summers** [comment]
@whitequark I have a fix that basically just `aborts()` the connection if an ACK is received after SYN (without the SYN bit set). The result is that the end user has to re-`connect()` the socket, but keeps the details and statefulness to a minimum in the `smoltcp` TCP implementation. Would we rather implement logic to restart the 3-way handshake after the RST is sent?

**Comment by whitequark** [comment]
> but keeps the details and statefulness to a minimum in the `smoltcp` TCP implementation.

I like this approach. If it turns out to be insufficient, we can always go for a more complex one later.
