### ISSUE TITLE
The `ping` example is currently broken.

### ISSUE THREAD

**Issue by batonius** [smoltcp-rs/smoltcp#37]
Right now the `ping` example panics on `iface.poll(&mut sockets, timestamp).expect("poll error")` because of `Error::Unaddressable` "thrown" in `EthernetInterface::lookup_hardware_addr`, which "unrolls" all the way up to `main`. 

The problem was introduced in 1ece71a when `socket_egress` stopped ignoring the error.

**Comment by whitequark** [comment]
Fixed.
