### ISSUE TITLE
Impossible to construct `phy::DeviceLimits`

### ISSUE THREAD

**Issue by phil-opp** [smoltcp-rs/smoltcp#39]
The `phy::DeviceLimits` struct has a private dummy field, which makes meaningful construction impossible. The only way is through the `Default` implementation, but this yields a `max_transmission_unit` of 0…

A `DeviceLimits` struct is required for implementing the `limits` method of the `phy::Device` trait.

**Comment by whitequark** [comment]
Something like:
```rust
DeviceLimits { max_transmission_unit: 1536, ..default() }
```
This is actually [in the docs](https://github.com/m-labs/smoltcp/blob/master/src/phy/mod.rs#L57-L62).

**Comment by phil-opp** [comment]
Thanks!
