### ISSUE TITLE
Use #[non_exhaustive] instead of manual __Nonexhaustive variants

### ISSUE THREAD

**Issue by whitequark** [smoltcp-rs/smoltcp#397]
It used to not be available in our MSRV, but that got bumped recently.

**Comment by Dirbaio** [comment]
`#[non_exhaustive]` was introduced in 1.40, our MSRV is 1.36. We shouldn't do this yet, right?

**Comment by whitequark** [comment]
1.40 is a year old by now, I would just bump MSRV to 1.40.

**Comment by niclashoyer** [comment]
I added a PR for this one. I'm not sure how MSRV is handled, though.
