### ISSUE TITLE
New crate.io release?

### ISSUE THREAD

**Issue by stlankes** [smoltcp-rs/smoltcp#412]
The latest crates.io release (version 0.6.0) is from Januar 2020. Are there any plans to release a new version?

**Comment by whitequark** [comment]
At the moment only I have crates.io permissions. @Dirbaio could you set up a team in the GitHub org that I could add to crate owners?

**Comment by Dirbaio** [comment]
[done](https://github.com/orgs/smoltcp-rs/teams/crates-io)!

**Comment by whitequark** [comment]
Hm, I'm having trouble with that crates.io interface again. It is so horribly unusable.
![Screenshot_20210119_102705](https://user-images.githubusercontent.com/54771/105021796-e0272280-5a40-11eb-91b2-a01758723904.png)

**Comment by stlankes** [comment]
I thought that `cargo owner --add github:smoltcp-rs:crates-io` is the way to do it.

**Comment by whitequark** [comment]
That produces the exact same error.

**Comment by stlankes** [comment]
Hm, does crates.io has oauth access to smoltcp-rs?

**Comment by whitequark** [comment]
Thanks for the pointer. Done now ([smoltcp](https://crates.io/crates/smoltcp), [managed](https://crates.io/crates/managed)).

**Comment by stlankes** [comment]
Thanks!

**Comment by whitequark** [comment]
For the onlookers, what I had to do was to revoke permissions for crates.io for my account, then re-login while granting access to smoltcp-rs. I have no idea whether that's documented anywhere other than in https://github.com/rust-lang/cargo/issues/5297.

**Comment by whitequark** [comment]
Actually, there's no release yet, I just set up the permissions, so reopening this.

**Comment by Dirbaio** [comment]
smoltcp 0.7 is now out! :tada:
