### ISSUE TITLE
0.7 build error

### ISSUE THREAD

**Issue by jiayihu** [smoltcp-rs/smoltcp#428]
I've just updated to `0.7` but I cannot build anymore:

```
error[E0004]: non-exhaustive patterns: type `(&Cidr, &Cidr)` is non-empty
   --> /Users/jiayihu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.7.0/src/wire/ip.rs:334:15
    |
334 |         match (self, subnet) {
    |               ^^^^^^^^^^^^^^
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `(&Cidr, &Cidr)`
```

These are the enabled features:

```
smoltcp = { version = "0.7.0", default-features = false, features = ["socket-udp", "socket-icmp"]}
```

Rust version:

```
rustc 1.50.0-nightly (593fe977a 2020-11-20)
```

**Comment by wbuck** [comment]
Yeah, when trying to use version `0.7` of the library I'm getting the following build errors:

    error[E0392]: parameter `'b` is never used 
    --> /Users/wbuck/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.7.0/src/socket/set.rs:182:21
        |
    182 | pub struct Iter<'a, 'b: 'a> {
        |                     ^^ unused parameter
        |
        = help: consider removing `'b`, referring to it in a field, or using a marker such as `PhantomData`


    error[E0392]: parameter `'a` is never used
      --> /Users/wbuck/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.7.0/src/socket/set.rs:13:17
       |
    13 | pub struct Item<'a> {
       |                 ^^ unused parameter
       |
       = help: consider removing `'a`, referring to it in a field, or using a marker such as `PhantomData`

    error[E0392]: parameter `'a` is never used
      --> /Users/wbuckley/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.7.0/src/socket/mod.rs:84:17
       |
    84 | pub enum Socket<'a> {
       |                 ^^ unused parameter
       |
       = help: consider removing `'a`, referring to it in a field, or using a marker such as `PhantomData`


Current features:
 `smoltcp = { version = "0.7", default-features = false, features = ["ethernet", "proto-ipv4"] }`

**Comment by whitequark** [comment]
@Dirbaio what should we do here, branch and release 0.7.1 with that fixed, or go straight to 0.8?

**Comment by Dirbaio** [comment]
I'll start a `v0.7.x` branch with all the non-breaking fixes. The NDISC one is also release-worthy.

**Comment by Dirbaio** [comment]
v0.7.1 is now out, with the fixes for feature combination issues!
