### ISSUE TITLE
Failed to build using `rustc 1.52.0-nightly (35dbef235 2021-03-02)`

### ISSUE THREAD

**Issue by jobenye** [smoltcp-rs/smoltcp#429]
As title, it happened to find the code can't be compiled using `rustc 1.52.0-nightly (35dbef235 2021-03-02)`. After switch back to the stable version, it works fine.

Steps to reproduce,
1. git clone <..>
2. the version is `commit c12fc6fbb08473a8b470b3bc736878ff9724ad83 (HEAD -> master, origin/master, origin/HEAD)`
3. rustup default nightly-x86_64-unknown-linux-gnu
4. cargo build

The errors looks like,
```
error: unknown `doc` attribute `shown`
  --> src/macros.rs:32:26
   |
32 |                   $( #[doc(shown)] $variant = $value ),+
   |                            ^^^^^
   |
  ::: src/wire/ethernet.rs:6:1
   |
6  | / enum_with_unknown! {
7  | |     /// Ethernet protocol type.
8  | |     pub enum EtherType(u16) {
9  | |         Ipv4 = 0x0800,
...  |
12 | |     }
13 | | }
   | |_- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unknown `doc` attribute `shown`
```

**Comment by Dirbaio** [comment]
Fixed in #434
