### ISSUE TITLE
DHCP client appears to duplicate request after an ACK

### ISSUE THREAD

**Issue by ryan-summers** [smoltcp-rs/smoltcp#438]
During the DHCP negotiation, the DHCP server appears to quickly respond to a DHCP REQUEST from the client. However, the client appears to ignore this DHCPACK and re-sends a DHCP REQUEST with a doubly incremented transaction ID:
![image](https://user-images.githubusercontent.com/8771450/110949290-b7d1eb00-8342-11eb-985e-172e655d8830.png)

The end result is still a functional DHCP client, but it appears that the client may be doing something wrong here internally.

**Comment by Dirbaio** [comment]
I can't reproduce this, I'm only seeing one request/ack cycle in my hardware.

Interesting that the repeated request is exactly 2 seconds after the first one. REQUEST_TIMEOUT is set to 1 second though. Strange.

Do you have more details? Smoltcp logs would be helpful.

**Comment by ryan-summers** [comment]
Yeah, this is on my TODO list to further debug, but there's some work I have to do to get logging up on our platform first. This is definitely blocked off more evidence from me.

**Comment by ryan-summers** [comment]
Note: This appears to be resolved by #459 as well
