### ISSUE TITLE
How to serve multiple TCP connections?

### ISSUE THREAD

**Issue by JakkuSakura** [smoltcp-rs/smoltcp#441]
TcpSocket implementation can only serve one client at a time. Moreover,`remote_endpoint` is not exposed as pub about ip address in TcpSocket. So how can I implement a normal web server with smoltcp?

**Comment by Dirbaio** [comment]
Unlike other TCP stacks there's no "TCP listener". To accept multiple connections, you need multiple sockets. Create a socket and call listen(). Once it receives a connection, create a second socket and call .listen(), etc. Serve connected sockets concurrently with waiting for the listening socket to receive a connection.

You can get the remote endpoint with the remote_endpoint() method.

**Comment by JakkuSakura** [comment]
Thanks for explaination, I know how it is going to work now.
