### ISSUE TITLE
Convert DHCP client to a socket

### ISSUE THREAD

**Issue by Dirbaio** [smoltcp-rs/smoltcp#446]
Currently the DHCP client uses RawSocket to send/receive packets. The RawSocket needs TX and RX buffers, which need to be 900 + 600 bytes = 1.5KB.

If the DHCP client could send and receive packets "on the fly", inside the Interface poll loop, it would use 1.5KB less of RAM.

The way to do this is make the DHCP client be a new socket type.

Thoughts? @whitequark

**Comment by whitequark** [comment]
> The way to do this is make the DHCP client be a new socket type.

I entirely agree with this, this is how I would have probably implemented it.
