### ISSUE TITLE
Edge case, TCP dropping next expected segment when Assembler is full (?)

### ISSUE THREAD

**Issue by loriopatrick** [smoltcp-rs/smoltcp#452]
Reading
https://github.com/smoltcp-rs/smoltcp/blob/43567b9743cb9f422de83fad9ff42a6d13f6e5ee/src/socket/tcp.rs#L1532-L1547

It appears possible to error when the payload_offest is 0. I think we should reserve a single position in the contig to ensure we can always accept a segment with offset 0. Another option would be to eject the segment with the highest offset however I think could have other ramifications (possibly in sACK logic).

Is it okay to drop packets with offset 0? From my limited experience with TCP I would think that could possibly lock up the protocol. Note, I haven't written a test to confirm this edge case does actually occur. I may be available to investigate further after working on sACK support.

**Comment by Dirbaio** [comment]
Oh yes, dropping a segment at offset=0 can definitely cause things to get stuck. Thanks for reporting!
