### ISSUE TITLE
DHCP replies with ICMP Port Unreachable when RawSocket buffer full

### ISSUE THREAD

**Issue by Dirbaio** [smoltcp-rs/smoltcp#457]
Right before the ACK, a random UDP broadcast arrives which occupies the only slot in the RawSocket buffer. When the ACK arrives, the RawSocket is full, so it doesn't accept the packet. smoltcp then replies with a "port unreachable". This probably shouldn't happen.

![screenshot-2021-04-01_15-42-35](https://user-images.githubusercontent.com/1247578/113304348-3b5b7800-9302-11eb-84c4-c3ba239f0637.png)

(DHCP doesn't retry the request after that and the device goes offline, but I think that's another bug...)

**Comment by ryan-summers** [comment]
I was observing this as well, thanks for figuring out the root cause here!

**Comment by Dirbaio** [comment]
Fixed in #459
