### ISSUE TITLE
Convert EthernetInterface to use a builder pattern

### ISSUE THREAD

**Issue by whitequark** [smoltcp-rs/smoltcp#47]
The type signature of `new` is getting _really_ unwieldy, and the breaking changes for every new features are undesirable.

**Comment by dlrobertson** [comment]
This is going to be super important as we move towards adding IPv6 support. Especially once builds without the future `proto-ipv4` become a possibility.

**Comment by dlrobertson** [comment]
In fact, this should probably be done before we add the `proto-ipv4` feature.
