### ISSUE TITLE
Udp rebinding / closing

### ISSUE THREAD

**Issue by ryan-summers** [smoltcp-rs/smoltcp#475]
It doesn't appear that smoltcp provides a mechanism to close or un-bind a UDP port (unless I'm missing something?).

As a result of this, once a UDP port has been bound, it may not be used for any other activities.

It would be beneficial to allow UDP ports to be re-bound to different sockets

**Comment by Dirbaio** [comment]
It is possible by removing the UdpSocket from the SocketSet entirely, and then adding a new one.

I do think a .close() makes sense though, it makes the UdpSocket API consistent with TcpSocket's, and makes closing easier depending on how user code is structured. PR welcome :)
