### ISSUE TITLE
Why is `std::error::Error` not implemented for `smoltcp::Error`?

### ISSUE THREAD

**Issue by JakkuSakura** [smoltcp-rs/smoltcp#484]
I'm trying to use `anyhow` to catch all errors in a simple example. However, 
```rust
error[E0277]: the trait bound `smoltcp::Error: std::error::Error` is not satisfied
   --> devourer/examples/dhcp_client.rs:110:41
    |
110 |         let x = tcp.recv_slice(&mut buf)?;
    |                                         ^ the trait `std::error::Error` is not implemented for `smoltcp::Error`
    |
    = note: required because of the requirements on the impl of `From<smoltcp::Error>` for `anyhow::Error`
    = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, smoltcp::Error>>` for `Result<(), anyhow::Error>`
    = note: required by `from_residual`

```
Is it because `smoltcp::Error` is oversimplied and discouraged to expose to external libraries? However, I see that smoltcp::Error is already `Display+Debug`, which `std::error::Error` only requires

**Comment by Dirbaio** [comment]
There's no particular reason it doesn't implement `std::error::Error`, it's probably just lack of demand since it can't be used in no-std code anyway. It could be implemented to be used in std-using code. PRs welcome :)
