### ISSUE TITLE
DHCPRepr doesn't include DNS servers when emitting

### ISSUE THREAD

**Issue by theli-ua** [smoltcp-rs/smoltcp#504]

**Comment by theli-ua** [comment]
Also, why is it always 3 ?????? rfc doesnt restrict amount of servers in any way

**Comment by Dirbaio** [comment]
It's 3 because that's the maximum seen in the wild, and since smoltcp is designed to work on systems without alloc we can't simply use a Vec there.

**Comment by theli-ua** [comment]
Would you take PR making Repr<dns: usize> const generic on number of DNS servers?

**Comment by Dirbaio** [comment]
The current MSRV is Rust 1.40 which doesn't have const generics.

What's your usecase for supporting more than 3 DNS servers? Maybe we can figure something out.

**Comment by theli-ua** [comment]
I don't have a specific one, was mostly just curious.

**Comment by theli-ua** [comment]
what about alloc feature though? (opt in, backwards compatible)

**Comment by Dirbaio** [comment]
Fixed in #505
