### ISSUE TITLE
Implementing IGMP protocol and multicast support

### ISSUE THREAD

**Issue by podhrmic** [smoltcp-rs/smoltcp#51]
Hello, for our application I need smoltcp to handle multicast packets (the application communicates  over multicast). I am happy to do that and implement this functionality to smoltcp, but I would like to get some pointers and guidance first.

1. IGMP protocol will have to be implemented - I would add another branch on the match expression here https://github.com/m-labs/smoltcp/blob/master/src/iface/ethernet.rs#L249 
2. Implement `EthernetProtocol::IGMP` with underlying logic
3. when IGMP (and multicast) is enabled we check `dst_addr()` against the list of multicast MAC addresses we are subscribed to (here: https://github.com/m-labs/smoltcp/blob/master/src/iface/ethernet.rs#L244 )
4. appropriately handle timeouts (see https://en.wikipedia.org/wiki/Internet_Group_Management_Protocol ) - not sure if we need a separate timer or we should use the time supplied to `iface.poll()`

 Does it sound like a good approach to you?

**Comment by whitequark** [comment]
Sounds good! I suggest working on it in small pieces and seeking review early, as I try to ensure the quality of code in smoltcp stays very high.

**Comment by whitequark** [comment]
@podhrmic This is done, right?

**Comment by podhrmic** [comment]
Yes, I believe IGMP support was added in #178
