### ISSUE TITLE
Please release v0.8 version

### ISSUE THREAD

**Issue by taikulawo** [smoltcp-rs/smoltcp#517]
It's confused me that `example/server.rs` use `InterfaceBuilder`, but latest 0.7.5 release has a renamed `EthenetInterfaceBuilder`.

![image](https://user-images.githubusercontent.com/24750337/128605453-6ce77b9e-5921-44d0-976d-a27cef4a12a7.png)

It's seems this PR has changed files, but no release pushed to cargo currently.
https://github.com/smoltcp-rs/smoltcp/pull/401

**Comment by Dirbaio** [comment]
There's still a few loose ends to tie before releasing 0.8

In the meantime you can refer to the examples at the [v0.7.5](https://github.com/smoltcp-rs/smoltcp/tree/v0.7.5/examples) tag, which match the v0.7.5 public API.
