### ISSUE TITLE
arp: fill cache only from ARP responses

### ISSUE THREAD

**Issue by Dirbaio** [smoltcp-rs/smoltcp#537]
This fill here fills the cache on any ARP message. It should only do it on  ARP responses I think.

https://github.com/smoltcp-rs/smoltcp/blob/db18514d46d7c6c1b4305b7e4c5560372806cc84/src/iface/interface.rs#L1044

**Comment by dnadlinger** [comment]
Isn't opportunistically use everything it sees to fill the cache a sensible thing to do?

**Comment by Dirbaio** [comment]
@dnadlinger In theory it's correct, but I'm quite scared that some broken network out there breaks it, similarly to what happened in 6210612be047ee706ac729015cdbc2581e6ae9a3. Addresses in ARP packets should be more reliable yes, but still, who knows...

Also it can fill the the ARP cache with random entries we don't need, which can evict the ones that we do need. So this change can be good for performance too.
