### ISSUE TITLE
arp: flush ARP cache when disconnecting or changing address

### ISSUE THREAD

**Issue by Dirbaio** [smoltcp-rs/smoltcp#543]
ARP cache should be flushed when

1. Our IP address changes
2. The interface goes down

Otherwise, the device may get plugged in into a network where eg router is still 192.168.1.1, but is another MAC addr. Communication might not work until the ARP cache entry expires.

**Comment by elpiel** [comment]
I suppose only the second point of this issue remains to be fixed after #564 was merged?
