### ISSUE TITLE
Possible typo in `Interface`'s `hardware_addr()`

### ISSUE THREAD

**Issue by jeehoonkang** [smoltcp-rs/smoltcp#583]
https://github.com/smoltcp-rs/smoltcp/blob/master/src/iface/interface.rs#L551-L552

These lines check exactly the same thing. I believe one of the two should check if the medium is IEEE 802.15.4.

**Comment by thvdveld** [comment]
Indeed, thanks for noticing! Also found the same mistake [here](https://github.com/smoltcp-rs/smoltcp/blob/master/src/iface/interface.rs#L572-L573). Fix is in #584 .
