### ISSUE TITLE
Panic in src/phy/sys/raw_socket.rs

### ISSUE THREAD

**Issue by witchof0x20** [smoltcp-rs/smoltcp#587]
I'm using smoltcp to ferry packets between two interfaces via raw sockets (with some custom filtering), and ran into this panic when stress-testing my program:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }',
 /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/raw_socket.rs:107:49
```
I see an explicit unwrap at https://github.com/smoltcp-rs/smoltcp/blob/master/src/phy/sys/raw_socket.rs#L107 :
```rust
if len == -1 {
    Err(io::Error::last_os_error()).unwrap()
}
```
and in the outer function that calls this at https://github.com/smoltcp-rs/smoltcp/blob/master/src/phy/raw_socket.rs#L114 :
```rust
lower..send(&buffer[..]).unwrap();
```

Is there a reason to explicitly panic here, or would it be reasonable to propagate that error up to the caller?

**Comment by Dirbaio** [comment]
Oh, raw socket send can WouldBlock under load? huh.

The cleanest solution is probably returning an error from `consume`, yes. This way the stack knows the send failed and can retry later.

Perhaps translate `Exhausted` to `WouldBlock`, and the others to `Illegal`
