### ISSUE TITLE
How do I set SO_MARK?

### ISSUE THREAD

**Issue by lazytiger** [smoltcp-rs/smoltcp#598]
Is it possible to set SO_MARK in smoltcp?

**Comment by Dirbaio** [comment]
I assume you're asking about the RawSocket PHY? It's not directly supported, but you can get the FD with `.as_raw_fd()` and then do`setsockopt()` on it yourself.

**Comment by lazytiger** [comment]
I want to set marks for all the packets coming from TapTunInterface, what should I do? Can I just setsockopt on TapTunInterface fd? Thanks

**Comment by Dirbaio** [comment]
I'm not sure it's possible with tun/tap. You can probably use iptables to mark all packets coming from `tap0`

**Comment by lazytiger** [comment]
I have tried the following iptables rules

iptables -t mangle -A OUTPUT -o tun0 -j MARK --set-mark 1

but no packets were matched

**Comment by Dirbaio** [comment]
Correct iptables usage is out of scope of smoltcp, I'm afraid.

**Comment by lazytiger** [comment]
Thanks for the reply.
