### ISSUE TITLE
IP version mismatch panic

### ISSUE THREAD

**Issue by jgallagher** [smoltcp-rs/smoltcp#599]
Hi! I was experimenting with the `master` branch, and code that was working with 0.8.0 is now panicking with something like

```
IP version mismatch: src=Unspecified dst=Ipv4(Address([192, 168, 69, 100]))
```

This is reproducible by running the `server` example on my machine and sending it data. `git bisect` points to 5989896 as the culprit. AFAICT, the chain of events is:

* A `UdpSocket` is created; `self.endpoint` is initialized to `Unspecified:0`.
* We call `.bind(port)` on the socket; `self.endpoint` is now set to `Unspecified:$PORT`.
* When we try to send on that socket, we hit [this panic introduced in that commit](https://github.com/smoltcp-rs/smoltcp/commit/5989896299d0ee03c829a6e600452ebae3b82588#diff-94a7f934fe66af30b7a65e53345991acde51441d760d711fd2c6812ec58e64f2R565).

This can be fixed on the client side by calling `.bind((specific_address, port))` - is that a requirement with these changes? If so, should `bind()` no longer accept only a port?

**Comment by Dirbaio** [comment]
This is definitely not intended, no.
