### ISSUE TITLE
`socket.listen()` clears previously-set settings such as keep-alive

### ISSUE THREAD

**Issue by mhils** [smoltcp-rs/smoltcp#601]
The following code behaves as expected:
```rust
let mut socket = TcpSocket::new(/* ... */);
socket.listen(dst_addr)?;
socket.set_keep_alive(Some(Duration::from_secs(30)));
dbg!(socket.keep_alive()) // Some(30s)
```

However, if we rearrange the calls to `listen` and `set_keep_alive`, the keep-alive value is forgotten:
```rust
let mut socket = TcpSocket::new(/* ... */);
socket.set_keep_alive(Some(Duration::from_secs(30)));
socket.listen(dst_addr)?;
dbg!(socket.keep_alive()) // None
```

This is unexpected as a similar reordering would work fine on Berkeley sockets. The reason for the behavior is that `socket.listen()` internally calls `socket.reset()`, which among other things clears the keep-alive value. The same problem also affects `ack_delay`, `hop_limit`, `nagle`, and `timeout`. 

I'm happy to submit a patch, but I don't know enough of smoltcp's internals to know what the intended fix should be:

1. Change `reset()` to not modify these values?
2. Do no call `reset()` in `.listen()`? (there already is a check for `is_open()`)?
3. Simply document that `listen()` must be called first?

**Comment by Dirbaio** [comment]
Thank for the report! This is indeed counterintuitive, fixing it sounds good.

I think `1. Change reset() to not modify these values?` is the best. It should be OK for `reset()` to  reset only the "state"  of the socket, but not all the "settings" that the user has configured.
