### ISSUE TITLE
6LowPan ICMPv6 NDISC errors

### ISSUE THREAD

**Issue by benbrittain** [smoltcp-rs/smoltcp#629]
I'm trying to get two microcontrollers to talk to each other over 805.15.4/6LowPan, both assigned static **site**-local IP addresses derived from the device's hardware address. I'm using site-local instead of link-local because I would like them to be routable through a border gateway. I'm attempting to send raw bytes over a udp socket to the other device. Because the device isn't in the neighbor cache, it appropriately triggers a ICMPv6 NDISC request, but after that things look a little weird to me.

The ICMPv6 type being output is 0, which I don't think is a valid type. This is from the `c4791eb668c421f941c4c489ba1a402162b7be93` commit of upstream.

```
TRACE - udp:fd00:1eaf::a08d:cfd3:fffe:bde1:7:fd00:1eaf::5ad3:fcc:fffe:7391:7: buffer to send 2 octets
TRACE - udp:fd00:1eaf::a08d:cfd3:fffe:bde1:7:fd00:1eaf::5ad3:fcc:fffe:7391:7: sending 2 octets
DEBUG - address fd00:1eaf::5ad3:fcc:fffe:7391 not in neighbor cache, sending Neighbor Solicitation
```

Here is the PCAP file from the sending side, renamed to a txt for github upload. You might need to disable the "Disect only good FCS" in the 802.15.4 protocol preferences since my radio peripheral calculates that after this is dumped.
[gateway.txt](https://github.com/smoltcp-rs/smoltcp/files/8886980/gateway.txt)

**Comment by benbrittain** [comment]
@thvdveld who has some context on this

**Comment by thvdveld** [comment]
I don't see how `smoltcp` can set all fields of the ICMPv6 packet, but not the type.
I think I'll require some help from @Dirbaio.

**Comment by benbrittain** [comment]
If you look at the bytes in the pcap file (and I confirmed with some printf debugging), It does call the set_type path, it's just not in the right place? I'm still rather fuzzy on how the compression iphc header stuff works, but you can see the `87` (Neighbor Solicitation type) on line `0020`

```
0000   41 c8 03 af 1e ff ff e1 bd fe ff d3 cf 8d a0 7b   A..............{
0010   39 3a fd 00 1e af 00 00 00 00 a0 8d cf d3 ff fe   9:..............
0020   bd e1 02 01 ff fe 73 91 87 00 92 37 00 00 00 00   ......s....7....
0030   fd 00 1e af 00 00 00 00 5a d3 0f cc ff fe 73 91   ........Z.....s.
0040   01 02 a0 8d cf d3 ff fe bd e1 00 00 00 00 00 00   ................
```

**Comment by thvdveld** [comment]
Could you share a link to your repository? I wrote a test for it and from the test it seems to work like expected.

**Comment by benbrittain** [comment]
The repository is a bit gnarly at the moment and depends on a bunch of local crates, but here is the setup code. The issue shouldn't be with the mcu radio stuff since this is dumped from smoltcp before we ever get to the write path of the radio peripheral.


https://gist.github.com/benbrittain/b10c228e369b19c7185a80750dc735fd

**Comment by benbrittain** [comment]
the IPv6 site-local address being generated for the radio peripheral is  `fd00:1eaf::a08d:cfd3:fffe:bde1/64`

**Comment by thvdveld** [comment]
Now my test fails indeed, I will try to figure out why it fails now!

**Comment by thvdveld** [comment]
@benbrittain could you check if #630 works for you?

**Comment by Dirbaio** [comment]
reopening pending confirmation it fixes OP's bug

**Comment by benbrittain** [comment]
wow, so speedy! Setting the microcontrollers back up (which I tore apart to test something else because I wasn't expecting this so quickly :sweat_smile: )

I do see something a little weird with the dumped packets in wireshark on the sending side though, it looks like maybe the checksum isn't being generated quite right?

![image](https://user-images.githubusercontent.com/207432/173382863-a56aa86c-63d1-4d85-ac7b-1fed1eb202cb.jpg)

**Comment by benbrittain** [comment]
![image](https://user-images.githubusercontent.com/207432/173386393-fe8fea48-4581-444b-8ebc-6e49f074cb2a.jpg)
That being said though, I do get valid UDP packets on the other side now! (we can ignore the bad FCS line) The checksum error is still present in the ICMP messages but it doesn't seem to be affecting anything.
