### ISSUE TITLE
Decouple sockets from interface

### ISSUE THREAD

**Issue by tsoutsman** [smoltcp-rs/smoltcp#643]
Hi,
I'm trying to port a crate from smoltcp version `0.5.0` to `0.8.1`. I have a global interface behind a static mutex. Previously I was using an `EthernetInterface` and `SocketSet`. I'd perform whatever operations I needed on the `SocketSet`, then lock the static mutex, and poll the interface using the `SocketSet`. The static mutex was only locked when polling the interface.

With the API changes, sockets are now directly added to interfaces. This means that the static mutex needs to be locked whenever I'm doing something with a socket which is less than ideal, as I have multiple processes using the static mutex. Is there a way around this?

**Comment by Dirbaio** [comment]
You're in luck! :) 

In git master (which will be 0.9) they're now separated again.
