### ISSUE TITLE
TCP test suites no longer assert when a packet is not received

### ISSUE THREAD

**Issue by SquidDev** [smoltcp-rs/smoltcp#659]
As of https://github.com/smoltcp-rs/smoltcp/commit/629f0bce7991bfb8e73aeeb3b39982338d0eb97b, it's possible for a socket's dispatch method to return `Ok(())` without ever emitting a packet. However, as the TCP test suite runs its assertions within the emit method, tests silently pass when they should not:

https://github.com/smoltcp-rs/smoltcp/blob/7d224457d2c8f0a42da0c291a74e85705fc439af/src/socket/tcp.rs#L2428-L2442

There's a couple of possible fixes I can see to this - happy to put a PR together if that's useful?
 - Synthesise an `Error::Exhausted` when the callback is not invoked.
 - Assert that the callback is invoked exactly once, and define a separate `recv_nothing` function to use when nothing should have been sent.

**Comment by Dirbaio** [comment]
Oh, interesting.

2nd fix (Assert that the callback is invoked exactly once) looks good to me.
