### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by rongyi** [smoltcp-rs/smoltcp#694]
https://github.com/smoltcp-rs/smoltcp/blob/master/src/storage/assembler.rs#L210

```
let mut assr = contigs![(0, 8), (4, 4)];
assert_eq!(assr.add(8, 4), Ok(false));
```

this testcase will panic at this line. I was just read smoltcp code, maybe the input is not valid, please correct me if I'm wrong.

**Comment by Dirbaio** [comment]
indeed it is...

another repro:


```rust

    #[test]
    fn test_lol() {
        let mut assr = Assembler::new(16);
        assert_eq!(assr.add(0, 1), Ok(false));
        assert_eq!(assr.add(2, 1), Ok(false));
        assert_eq!(assr.add(1, 1), Ok(false));
    }
```

**Comment by Dirbaio** [comment]
Thanks for finding and reporting it! :)

**Comment by rongyi** [comment]
@Dirbaio pleasure!
