### ISSUE TITLE
How to actively open a TCP connection?

### ISSUE THREAD

**Issue by little-dude** [smoltcp-rs/smoltcp#7]
After looking at the doc and at the code, I could not find out how to actively open a TCP connection. Is this implemented? If so, how can it be done?

**Comment by little-dude** [comment]
From the doc, it seems that it's there though:

> A TCP socket may passively listen for connections *or actively connect to another endpoint*.

**Comment by whitequark** [comment]
> From the doc, it seems that it's there though:
> 
> A TCP socket may passively listen for connections or actively connect to another endpoint.

It's kinda not. Almost all of the machinery is there but I never implemented the front-end method for connecting somewhere.

**Comment by whitequark** [comment]
Fixed in 1a32b98b.

**Comment by whitequark** [comment]
@little-dude Please see the README for an example of using the TCP client feature.
