### ISSUE TITLE
elided lifetime for the return value of `tcp::Socket::peek()` limits "async" usage

### ISSUE THREAD

**Issue by nerditation** [smoltcp-rs/smoltcp#761]
in short: I think the returned slice of `Socket<'a>::peek()` should have `'a` lifetime (i.e. the `ManagedSlice` of the ring buffer), instead of the elided lifetime (which is the same as `self`), and same for the `RingBuffer::get_allocated()`:

https://github.com/smoltcp-rs/smoltcp/blob/bd2086527bf9c1413ea6100d7cc401590499398b/src/socket/tcp.rs#L1160

https://github.com/smoltcp-rs/smoltcp/blob/bd2086527bf9c1413ea6100d7cc401590499398b/src/storage/ring_buffer.rs#L352

usually, this is fine, because the lifetime `self` is not limited, (also, `recv()` and `send()` won't be affected, since they don't "leak" direct reference of the underlying ring buffer). but it would cause problem when you want to wrap the `peek()` method for a `Future` wrapper type.

that said, I think this is *NOT* a big problem, as `peek()` is not being used very often I think, and the same functionality can be achived using `recv()` with an extra buffer anyway.

--------------------------
long description:

I was making an "async" wrapper for `tcp::Socket`. I managed to get `send()` and `recv()` to work, but I can't make `peek()` work. because a `Future` can't directly store a reference to a `tcp::Socket` object, as the socket reference borrows the socket set, and the socket set is shared over many places, the future stores a shared reference (behind an async mutex) to the socket set, along with the socket handle. when the future got polled, it simply looks up the socket from the socket set and polls the socket via `tcp::Socket::can_recv()`. something like this (simplified, an alternative implementation could change the `Output` type and do the work in the `poll` method directly instead of only polling for `can_recv()`, but the problem is the same):
```rust
/// this future doesn't implement Send and only be spawned on single threaded executors
struct Readable<'b> {
	socket_set: Rc<Mutex<iface::SocketSet<'b>>>,
	handle: iface::SocketHandle,
}
impl<'a, 'b> Future for Readable<'a, 'b> {
	type Output = ();
	fn poll(
		self: std::pin::Pin<&mut Self>,
		cx: &mut std::task::Context<'_>,
	) -> Poll<Self::Output> {
		let guard = self.socket_set.lock();
		let guard = std::pin::pin!(guard);
		let socket_set = futures_lite::ready!(guard.poll(cx));
		let socket = socket_set.get_mut::<tcp::Socket>(self.handle);
		if socket.can_recv() {
			Poll::Ready(())
		} else {
			socket.register_recv_waker(cx.waker());
			Poll::Pending
		}
	}
}

// this works
async fn recv<'b>(set: Rc<Mutex<SocketSet<'b>>>, handle: SocketHandle, buf: &mut [u8])  {
	Readable {set: set.clone(), handle}.await;
        // can_recv() is true now
        set.lock().await.get_mut::<tcp::Socket>::(handle).recv_slice(buf);
}

// this doesn't
async fn peek<'b>(set: Rc<Mutex<SocketSet<'b>>>, handle: SocketHandle, size: usize) -> &'b ??? [u8] {
	Readable {set: set.clone(), handle}.await;
        // can_recv() is true now
        set.lock().await.get_mut::<tcp::Socket>::(handle).peek(buf).unwrap()
}
```

 the reference to the socket itself has limited scope and is short lived. 

Edit: I searched the issues about lifetime, #695 seams related but it's about `SocketSet`, not `tcp::Socket` and `RingBuffer`.

**Comment by Dirbaio** [comment]
This would be unsound. the user would be able to hold on to the returned slice as a `&[u8]`, then pop these bytes off the buffer, allowing the TcpSocket to overwrite them. It is unsound to have something else write to the buffer while the user is holding a `&[u8]` or `&mut [u8]` to it.

**Comment by nerditation** [comment]
you are absolute right. I forgot that although there's lifetime marker in the `tcp::Socket` type, conceptually it owns the underlying buffer, (technically it is an exclusive borrow, or mutable reference in `ManagedSlice`, not actually owner ship).

 I always find lifetimes in async context difficult, as the desugar transform breaks the apparent connection between lifetime and scopes, I must think really carefully, it is not as intuitive as I would like. anyway, sorry for the noise, and many thanks for your explanation.
