### ISSUE TITLE
DNS Private Enums

### ISSUE THREAD

**Issue by wmcleish** [smoltcp-rs/smoltcp#762]
Hi there, I'm trying to use the wire::DnsPacket functions set_opcode and set_flags which take the Opcode and Flags enums respectively. Unfortunately, the parameter types are enums defined in wire::dns which is private. I've attempted to access them through DnsPacket, DnsRepr, and DnsQueryType, but am unable to. Is there any reason why these are not accessible to the user of DnsPacket?

**Comment by Dirbaio** [comment]
Probably an oversight. Can you send a PR?
