### ISSUE TITLE
[ASK] Ethernet Frame struct

### ISSUE THREAD

**Issue by LuoZijun** [smoltcp-rs/smoltcp#77]
Code Lines: https://github.com/m-labs/smoltcp/blob/master/src/wire/ethernet.rs#L88-L91

The wiki page: https://en.wikipedia.org/wiki/Ethernet_frame#Structure

as you can see, wikipedia said ethernet frame after `payload` filed, have one `Frame check sequence (32‑bit CRC)` field , but i have not see in we `ethernet frame struct` .

**Comment by whitequark** [comment]
The frame check sequence, just like the preamble and start delimiter, are handled by hardware.

**Comment by whitequark** [comment]
Note the difference between ethernet _packet_ and ethernet _frame_; the packet includes preamble and FCS, whereas the frame does not.

**Comment by LuoZijun** [comment]
@whitequark 

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/717717/32592967-f7c2ae8c-c560-11e7-9522-e7e759a10eab.png">

thx, the wikipedia lie to me -_-

**Comment by LuoZijun** [comment]
@whitequark 

now the wikipedia page [Ethernet_frame](https://en.wikipedia.org/wiki/Ethernet_frame) have been fixed 😄

**Comment by whitequark** [comment]
Looks like the Wikipedia people disagree: https://en.wikipedia.org/w/index.php?title=Ethernet_frame&diff=809483347&oldid=809464039
Oh well. In any case, it's virtually always handled by hardware, so there is no point in exposing it to software.

**Comment by LuoZijun** [comment]
okay
