### ISSUE TITLE
Can an Interface poll multiple SocketSet now?

### ISSUE THREAD

**Issue by StevenJiang1110** [smoltcp-rs/smoltcp#779]
For example, I want to use one interface to poll first SocketSet first and then poll second SocketSet, can the `interface` determine which `SocketSet` the received packet is from?

**Comment by Dirbaio** [comment]
No, you must have 1 Interface = 1 SocketSet, and add all sockets to that SocketSet. When polling, incoming packets are distributed to the sockets in the socketset, or immediately discarded if none matches.

**Comment by StevenJiang1110** [comment]
Thanks for your explanation.
