### ISSUE TITLE
What is the difference between using Loopback with Ethernet medium versus using Loopback with IP medium?

### ISSUE THREAD

**Issue by StevenJiang1110** [smoltcp-rs/smoltcp#780]
Now, when creating a Loopback device, it is necessary to specify the medium. I hope to send and receive TCP/UDP sockets on a Loopback device. Is there any difference in using these two mediums? The difference between these two mediums should be at the IP layer, but there should be no difference at the transport layer, right?

**Comment by thvdveld** [comment]
When using the Ethernet medium, packets will be transmitted using Ethernet frames. It is then also required to let the interface know what the Ethernet address is. When using the IP medium, no link layer is used. The transport layer is untouched by the used medium.

**Comment by StevenJiang1110** [comment]
Thanks a lot
