### ISSUE TITLE
examples/dhcp_client.rs is misleading/wrong

### ISSUE THREAD

**Issue by pdh11** [smoltcp-rs/smoltcp#783]
As of 0.9.1 and current main 8b0c521e2, the "dhcp_client.rs" example, when it gets a Configured event, attempts to set the interface's IPv4 address as follows:

```rust
fn set_ipv4_addr(iface: &mut Interface, cidr: Ipv4Cidr) {
    iface.update_ip_addrs(|addrs| {
        let dest = addrs.iter_mut().next().unwrap();
        *dest = IpCidr::Ipv4(cidr);
    });
}
```

This doesn't actually work in Smoltcp 0.9.1, because iter_mut() on a heapless::Vec iterates only over the _existing_ items, and is incapable of adding one if the Vec is currently empty. It always panics unwrapping the error from next(). This code worked in 0.8.x because iter_mut() on a mutable slice (which is what ManagedSlice derefs to) _does_ iterate over all elements (which were set to UNSPECIFIED if not currently in use).

For smoltcp 0.9.x, set_ipv4_addr should probably do something like:
```rust
                iface.update_ip_addrs(|addrs| {
                    addrs.push(IpCidr::Ipv4(config.address)).unwrap();
                });
```
and likewise on a Deconfigured event it should do addrs.clear().

**Comment by jlogan03** [comment]
@pdh11 thanks for making this issue! This probably saved me another 6 hours of troubleshooting while thinking this was a problem with my network switch. I made #905 to fix this, and have a piece of firmware based on those fixes running on a board now w/ IP address acquired successfully.
