### ISSUE TITLE
so bad performance, echo example is very slow?

### ISSUE THREAD

**Issue by centny** [smoltcp-rs/smoltcp#795]
#### start server
* start server by `cargo run --example server -- --tap tap0`
* already change `examples/utils.rs` log level to `LevelFilter::Info`

#### try 1: defautl code resuts if 
<img width="518" alt="image" src="https://github.com/smoltcp-rs/smoltcp/assets/4049551/6e16cc42-0894-4a70-83d1-e74d3defd430">

#### try 2: change rx/tx buffer to 65535
```.rs
    let tcp2_rx_buffer = tcp::SocketBuffer::new(vec![0; 65535]);
    let tcp2_tx_buffer = tcp::SocketBuffer::new(vec![0; 65535]);
```
<img width="523" alt="image" src="https://github.com/smoltcp-rs/smoltcp/assets/4049551/457217aa-ec45-41e8-be0f-2060e6e85f7c">

#### try 3: disable reverse data
```.rs
            let data = socket
                .recv(|buffer| {
                    let recvd_len = buffer.len();
                    let mut data = buffer.to_owned();
                    // if !data.is_empty() {
                    //     debug!("tcp:6970 recv data: {:?}", data);
                    //     data = data.split(|&b| b == b'\n').collect::<Vec<_>>().concat();
                    //     data.reverse();
                    //     data.extend(b"\n");
                    // }
                    (recvd_len, data)
                })
                .unwrap();
```
<img width="492" alt="image" src="https://github.com/smoltcp-rs/smoltcp/assets/4049551/19756cda-4908-485e-8dad-e13b5b9cf674">

#### try 4: only recv
```.rs
            let data = socket
                .recv(|buffer| {
                    let recvd_len = buffer.len();
                    let mut data = buffer.to_owned();
                    // if !data.is_empty() {
                    //     debug!("tcp:6970 recv data: {:?}", data);
                    //     data = data.split(|&b| b == b'\n').collect::<Vec<_>>().concat();
                    //     data.reverse();
                    //     data.extend(b"\n");
                    // }
                    (recvd_len, data)
                })
                .unwrap();
            // if socket.can_send() && !data.is_empty() {
            //     debug!("tcp:6970 send data: {:?}", data);
            //     socket.send_slice(&data[..]).unwrap();
            // }
```
<img width="430" alt="image" src="https://github.com/smoltcp-rs/smoltcp/assets/4049551/3c0a490b-a342-46fe-9b25-36ded61d2669">

#### try 5: --release
<img width="447" alt="image" src="https://github.com/smoltcp-rs/smoltcp/assets/4049551/2a06794a-d0b4-4301-bd52-89eceaccdf7c">

#### the test client code
* `go run test.go`

```.go
package main

import (
	"fmt"
	"net"
	"os"
	"time"
)

func speedConn(conn net.Conn, action string) (err error) {
	buf := make([]byte, 8*1024)
	n := 0
	lastAll := []int64{}
	lastTime := time.Now()
	lastBytes := int64(0)

	for {
		if action == "R" {
			n, err = conn.Read(buf)
		} else {
			n, err = conn.Write(buf)
		}
		if err != nil {
			break
		}
		lastBytes += int64(n)
		if time.Since(lastTime) > time.Second {
			lastAll = append(lastAll, lastBytes)
			if len(lastAll) > 5 {
				lastAll = lastAll[1:]
			}
			lastBytes = 0
			lastTime = time.Now()
			lastTotal := int64(0)
			for _, v := range lastAll {
				lastTotal += v
			}
			lastAvg := lastTotal / int64(len(lastAll))
			if lastAvg > 1024*1024*1024 {
				fmt.Printf("%v %v GB/s\n", action, float64(lastAvg)/1024/1024/1024)
			} else if lastAvg > 1024*1024 {
				fmt.Printf("%v %v MB/s\n", action, float64(lastAvg)/1024/1024)
			} else if lastAvg > 1024 {
				fmt.Printf("%v %v KB/s\n", action, float64(lastAvg)/1024)
			} else {
				fmt.Printf("%v %v B/s\n", action, float64(lastAvg))
			}
		}
	}
	return
}

func main() {
	conn, err := net.Dial("tcp", os.Args[1])
	if err != nil {
		panic(err)
	}
	go speedConn(conn, "W")
	speedConn(conn, "R")
}
```

**Comment by Dirbaio** [comment]
Compile with `--release`.

**Comment by centny** [comment]
@Dirbaio try it, better
<img width="447" alt="image" src="https://github.com/smoltcp-rs/smoltcp/assets/4049551/a7775bab-7710-413a-90e5-774639db3c36">

**Comment by Dirbaio** [comment]
my results:
- setting log level to info, increasing tcp buffer to 65536, running with --release:
```
[dirbaio@mars smoltcp]$ go run test.go 192.168.69.1:6970
R 171.18649768829346 MB/s
W 178.171875 MB/s
R 169.0466833114624 MB/s
W 175.515625 MB/s
R 159.88054370880127 MB/s
```

trying the same on 6971, which only receives:

```
[dirbaio@mars smoltcp]$ go run test.go 192.168.69.1:6971
W 655.328125 MB/s
W 628.37890625 MB/s
W 620.4973955154419 MB/s
W 605.966796875 MB/s
W 599.6374998092651 MB/s
W 584.1624994277954 MB/s
```

That's approx ~5gbit. It's about the performance to be expected out of a tun/tap interface, these are somewhat inefficient because they require a system call for each packet. If you check with `perf`, a lot of the CPU time is spent entering/exiting syscalls:

![screenshot-2023-06-09_12-51-42](https://github.com/smoltcp-rs/smoltcp/assets/1247578/14b7f2ff-6ec3-46ff-9cd0-d08301b04ade)


Laptop with i7-8850H, Linux 6.3.4-arch2-1.

**Comment by centny** [comment]
@Dirbaio thinks. it is ok, try compare it with lwip. it is better performance to lwip. may be the vm server problem.
