### ISSUE TITLE
IpEndpoint should have a FromStr implementation

### ISSUE THREAD

**Issue by dlrobertson** [smoltcp-rs/smoltcp#81]
IpEndpoint does not currently have a `FromStr` implementation or `Parser::accept_ip_endpoint` implementation.

Per the suggestion by @batonius.
 
> ... it's trivial to split an IPv4 endpoint at ':', IPv6 endpoints are quite tricky: https://tools.ietf.org/html/rfc5952#section-6 . I think the recommended style would be enough, it's the only one std::net::SocketAddrV6 supports: https://doc.rust-lang.org/nightly/src/std/net/parser.rs.html#280

Original comment: https://github.com/m-labs/smoltcp/pull/72#issuecomment-344077253

**Comment by hjr3** [comment]
I am working on this and should have a PR up in a few days.

**Comment by whitequark** [comment]
Cool! Thank you.
