### ISSUE TITLE
Contributing - is project still active?

### ISSUE THREAD

**Issue by oslfmt** [smoltcp-rs/smoltcp#818]
I'd like to possibly contribute to this project - is it still actively maintained?

**Comment by crawford** [comment]
Yep. Send over your patches. There are a number of folks who will review them.

**Comment by oslfmt** [comment]
Great! I'll take a look at the issues and start work on one - any particularly pressing issues?

**Comment by pothos** [comment]
Not pressing but nice to have for reliable operation are the "not implemented", "not supported" parts of TCP: https://github.com/smoltcp-rs/smoltcp#tcp-layer
Silly window syndrome avoidance and Probing Zero Windows are both not too large in scope but require some RFC reading and thinking. Selective acknowledgements is probably a bit larger.
Someone even started congestion control, not sure where the old branch is but you could also take one of the BBR implementations from a Go network stack for comparison.
