### ISSUE TITLE
Add support for tun interface?

### ISSUE THREAD

**Issue by raintean** [smoltcp-rs/smoltcp#82]

**Comment by whitequark** [comment]
What's the point?

**Comment by LuoZijun** [comment]
@whitequark i think his mean is platform api ( `phy` ) .

**Comment by whitequark** [comment]
Yes. Tap interfaces are software emulation of layer 2 interfaces (Ethernet in our case) so we can handle them with EthernetInterface. However, tun interfaces are software emulation of layer 3 interfaces (TCP/UDP/IP directly), so we would need an alternative to EthernetInterface that works on layer 3. We can implement that, but why should we?

**Comment by LuoZijun** [comment]
@whitequark as i know, the `phy` module is `RAW_SOCKET` api work on  bsd/linux/windows platforms. 

why we need `phy` module ? beacuse we need send some ethernet frame packet(tap) or ip packet(tun)  to `netif` device (just like `iface` module).

in unix-like system, they have 3 types `netif` device: loopback, tap and tun.

for now, we just impl `loopback` and `tap` on linux platform, if we has implemented `tun` device, that is good for some VPN user.

of course, they can use third party lib, like (meh/rust-tun)[https://github.com/meh/rust-tun] .

**Comment by whitequark** [comment]
If you just want the `phy::tun` module, I am fine with that. Please feel free to implement it and submit as a PR, and I will merge it.

**Comment by LuoZijun** [comment]
@whitequark okay, i try.

**Comment by liranringel** [comment]
@LuoZijun any progress?
Let me know if you're still into it.

**Comment by LuoZijun** [comment]
@liranringel 

https://github.com/LuoZijun/exodus/blob/master/netif/src/bpf.rs

i'm try port `bpf` on macOS.

this also can also resolve [issues/71](https://github.com/m-labs/smoltcp/issues/71)

**Comment by LuoZijun** [comment]
@liranringel 

See [PR-136](https://github.com/m-labs/smoltcp/pull/136) .

**Comment by Dirbaio** [comment]
TUN is supported since 0.8
