### ISSUE TITLE
Read RFC 9293 vs RFC 793

### ISSUE THREAD

**Issue by oslfmt** [smoltcp-rs/smoltcp#824]
The beginning of the `tcp.rs` file states:

```Heads up! Before working on this file you should read, at least, RFC 793```

But this rfc has been obsoleted by rfc 9293. Any reason why we should still refer to the older rfc?

**Comment by Dirbaio** [comment]
No reason, other than that code was written before RFC 9293 existed :)

**Comment by oslfmt** [comment]
Ahhh ok haha
