### ISSUE TITLE
Sensible defaults for DeviceCapabilities

### ISSUE THREAD

**Issue by phil-opp** [smoltcp-rs/smoltcp#85]
Currently, `DeviceCapabilities` _derives_ `Default`, which results in a MTU of 0. Wouldn't it make more sense to provide a manual `Default` implementation with a reasonable default?

**Comment by whitequark** [comment]
Sure.

**Comment by whitequark** [comment]
I've thought about it and there's no *reasonable default* for MTU. For other fields we already have those.
