### ISSUE TITLE
`Ipv6Packet::scope` and `Scope` is private

### ISSUE THREAD

**Issue by kgv** [smoltcp-rs/smoltcp#897]
Constructor `std::net::SocketAddrV6::new` takes `scope_id: u32`, but `Scope` and `Ipv6Packet::scope` method is `pub(crate)`.
Maybe should change it to `pub`.

**Comment by thvdveld** [comment]
I think you mean [`Ipv6Address::scope`](https://github.com/smoltcp-rs/smoltcp/blob/67f0528b1408ce10ed6a3932df06df25cf2ceb7c/src/wire/ipv6.rs#L28-L48). This is used for the multicast scope of the IPv6 address, which is not the same as scope id for the socket.
