### ISSUE TITLE
How to make IPv6 handle any ip

### ISSUE THREAD

**Issue by Skyxim** [smoltcp-rs/smoltcp#899]
https://github.com/smoltcp-rs/smoltcp/blob/9bd836ba6555c813b5b132f24316b02fa56510b8/src/iface/interface/ipv6.rs#L192-L194

Due to the addition of filtering, but no support similar to any_ip in IPv4, all unicast destination addresses that are not the current interface are now lost.

I don’t know if there is any way to solve it?

**Comment by thvdveld** [comment]
Could you check if #900 fixes your issue? It uses the same any_ip flag to allow any IP in IPv6.

**Comment by Skyxim** [comment]
> Could you check if #900 fixes your issue? It uses the same any_ip flag to allow any IP in IPv6.

Solved, it can be used like version 0.10.0
