### ISSUE TITLE
Proposal: Improve the routing table by radix tree

### ISSUE THREAD

**Issue by hainesc** [smoltcp-rs/smoltcp#915]
I noticed that recently the routing table is a list of CIDR, see https://github.com/smoltcp-rs/smoltcp/blob/main/src/iface/route.rs#L68.

It is simple, but is not that high-performance, I know that the best solution for routing table may be radix tree, it was implemented in may other platforms.

**Comment by thvdveld** [comment]
I think that it is not necessary yet to have the routing table implementation as a radix tree, as it usually only contains the gateway address.
